### ISSUE TITLE
add PPC support

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration#16]
Hey @shenki , do you have a set of configs that we can add for PPC? Probably can be modeled on @nathanchance 's patches in #14 ?

**Comment by nathanchance** [comment]
2b76ea23aaca9813317c64d4239cb5f0e032aea1 too

**Comment by nickdesaulniers** [comment]
cc @daxtens

**Comment by daxtens** [comment]
So you want to distinguish between 3 different flavours of PowerPC: 64-bit LE, 64-bit BE and 32-bit. @shenki has done lots of work for the first and third, and I've done a little bit on the second. I'm mostly working from a particularly slimmed down config for the paticular dev board I have, so that's probably not what you want to build from. You probably want ppc64_defconfig with whatever bits are still broken disabled.

**Comment by shenki** [comment]
WIP: https://github.com/shenki/continuous-integration/tree/ppc64le

Currently it contains hand-built binaries to get the build running on the outdated base distro.

We need a better solution for bringing in newer binutils and qemu. I've had success in the past using Travis but do the entire build inside a container running an up to date distro.

**Comment by nathanchance** [comment]
Yeah, having access to a rolling release distro like Arch would be really nice so all of our packages are up to date. That would be nice for arm64 so we could test LSE atomics support. I'll try to take a look at this today.

**Comment by nathanchance** [comment]
Hmmm actually we'll want to stick with Debian/Ubuntu given that the LLVM/Clang nightlies are only available on there. Stretch seems like a good candidate since it has an official Docker image: https://hub.docker.com/r/_/debian/

@shenki would [binutils 2.28](https://packages.debian.org/stretch/binutils-powerpc-linux-gnu) be good enough? I suppose if we needed the latest, we could just use Debian unstable (sid). Stretch also has [QEMU 2.8](https://packages.debian.org/stretch/qemu-system-ppc).

Only downside I see with switching to Docker is the ability to cache ccache (I think, unless we want to keep using the same docker image).

**Comment by nickdesaulniers** [comment]
If docker simplifies things, let's do that. I just have no experience with
it, but we can fix that.

**Comment by nathanchance** [comment]
I've picked it up fairly quickly. Luckily, I had a GCE trial still so I could have access to a Trusty enviroment.

What I like about it is we get a totally deterministic environment every time. This should work for Travis I think (will push to test here shortly).

```
sudo docker create -v ${TRAVIS_BUILD_DIR}:/travis --name travis debian
sudo docker run --env ARCH=${ARCH} --env LD=${LD} --rm --volumes-from travis debian /bin/bash -c 'apt-get update
apt-get upgrade -y
apt-get install -y bc binutils bison ccache curl flex expect gcc git gnupg libssl-dev openssl make qemu-system-arm qemu-system-x86 
curl https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
echo "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch main" | tee -a /etc/apt/sources.list
apt-get update -qq
apt-get install -y clang-8 lld-8
cd /travis
./driver.sh'
```

**Comment by nathanchance** [comment]
Just running x86_64 works: https://travis-ci.com/ClangBuiltLinux/continuous-integration/builds/90309229

I've started a full build based on [this commit](https://github.com/ClangBuiltLinux/continuous-integration/commit/15a2288da77cdcfe53944c0e629e3bbb49e69d4e): https://travis-ci.com/ClangBuiltLinux/continuous-integration/builds/90314739

**Comment by shenki** [comment]
Nice. I rebased on your tree and gave it a go. Qemu 2.8 is too old to boot a powernv kernel (the bootloader, skiboot, tries to clear some state that Qemu didn't model, causing qemu to abort).

I am re-trying with sid now: https://travis-ci.org/shenki/continuous-integration/builds/451119538

**Comment by nathanchance** [comment]
Perfect. If sid works, then I'll add it to the current docker pull request I have pending and I'll pull in the organization of https://github.com/shenki/continuous-integration/commit/31005d3deda4d620d94ee6f3bdd9db2d488e4ea7 since that seems reasonable.

**Comment by shenki** [comment]
Sid ships Qemu 2.12, which still doesn't boot the upstream kernel. We need https://github.com/qemu/qemu/commit/6b37554458a1e8cfe8f91ef0beac82e8de8f85bb which is in v3.0.

**Comment by nickdesaulniers** [comment]
Is there a protocol for asking that a debian package be rebuilt from updated source, or is that an exercise in signing up to be the new maintainer?

**Comment by shenki** [comment]
I think we could proceed with our own qemu binary, either from a PPA or a binary that we download. I can do the work to produce either; do we have a preference?
