### ISSUE TITLE
verify we can build WITHOUT GCC in the env

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration#66]
we should triple check that we can build WITHOUT gcc at all in the env to make sure nothing from KBUILD is leaking. `apt remove gcc` and then verify gcc is not in the `$PATH` would be good.

**Comment by nathanchance** [comment]
I just verified it locally with `docker run --rm -ti nathanchance/cbl`, `apt remove cpp gcc`, `./driver.sh`, plus this diff:

```diff
diff --git a/driver.sh b/driver.sh
index 17d54d2..566315b 100755
--- a/driver.sh
+++ b/driver.sh
@@ -87,7 +87,7 @@ setup_variables() {
 
 check_dependencies() {
   command -v nproc
-  command -v gcc
+  ! command -v gcc
   command -v "${CROSS_COMPILE:-}"as
   command -v "${CROSS_COMPILE:-}"ld
   command -v ${qemu}
```

**Comment by nickdesaulniers** [comment]
anything else to change in `.travis.yml` to say "no gcc, please?"

**Comment by nickdesaulniers** [comment]
also, `! command -v gcc` doesn't do what I'd expect it to do.

Locally:
```sh
$ ! command -v hello
$ echo $?
0
$ which hello
hello not found
$ echo $?    
1
```

**Comment by nathanchance** [comment]
> anything else to change in `.travis.yml` to say "no gcc, please?"

We should probably add `apt remove cpp gcc` and `! command -v gcc` to `debian-setup.sh` since we just need to have GCC unavailable in the container.

> also, `! command -v gcc` doesn't do what I'd expect it to do.
> 
> Locally:
> 
> ```shell
> $ ! command -v hello
> $ echo $?
> 0
> $ which hello
> hello not found
> $ echo $?    
> 1
> ```

Seems like it's working to me. The negation means that we want the command to pass when GCC is unavailable.

```
$ command -v hello
$ echo $?
1
$ ! command -v hello
$ echo $?
0
```

**Comment by nickdesaulniers** [comment]
> Seems like it's working to me. 

```sh
➜  linux-4.9 git:(clang-4.9) $SHELL --version
$SHELL --version
zsh 5.5 (x86_64-debian-linux-gnu)
```

a bug in zsh?

**Comment by nathanchance** [comment]
Sorry, I just thought of a better way to state my point. Your comparison isn't apples to apples since `command -v` is to `which` not `! command -v` is to `which`.

**Comment by tpimh** [comment]
Hope building without GNU binutils, only using LLVM tools will be possible soon.

**Comment by nickdesaulniers** [comment]
That's the goal ;)

**Comment by tpimh** [comment]
As of now https://github.com/ClangBuiltLinux/linux/issues/33 is a huge blocker. I will try to investigate tomorrow. I also don't know if cross-compilation would be easy (or even possible) without GNU binutils.

**Comment by nathanchance** [comment]
I'd argue `-fno-integrated-as` is the ultimate blocker since we'll need `as` as long as that is around but regardless, I'd say getting `lld` to work properly in lieu of `ld` seems like a more reasonable "short term" goal (given that it's already working on arm64, [close](https://github.com/ClangBuiltLinux/continuous-integration/pull/59) on x86_64, and has [some movement](https://github.com/ClangBuiltLinux/linux/issues?utf8=%E2%9C%93&q=label%3A%22%5BARCH%5D+powerpc%22+label%3A%22lld%22) on ppc).

**Comment by tapaswenipathak** [comment]
Hi @nathanchance, are you still working on it? Is there any Slack channel for communication about tickets as I think I end up commenting on many tickets today.

**Comment by nathanchance** [comment]
@tapaswenipathak thanks for the ping, this has been fixed: https://github.com/ClangBuiltLinux/dockerimage/commit/99b0f1a791af1bb849b86e2d10507a60edfaad86

I have considered setting up some sort of chat for us to do real time chat but GitHub seems to work fine so far.

**Comment by nickdesaulniers** [comment]
> I have considered setting up some sort of chat for us to do real time chat but GitHub seems to work fine so far.

I like IRC.  I think there's also something else that does GH integration, FWIW.

**Comment by nathanchance** [comment]
I am fairly certain that Slack and Discord have some GitHub integration things.

**Comment by tapaswenipathak** [comment]
Gitter is also an option, the best GitHub integration I have observed.

**Comment by tapaswenipathak** [comment]
Gitter is great in GitHub integration, Slack has nicer UI though. IRC is minimalist kind of a thing. Discord is fine. I would say Gitter, if people outside this org will work on this project otherwise any.

**Comment by nathanchance** [comment]
Huh interesting, never heard of Gitter before: https://gitter.im/

Made by Gitlab. I'm most familiar with Slack and Discord, which I've used for other projects. Apparently, Discord doesn't have Travis CI integration like I thought (https://github.com/travis-ci/travis-tasks/pull/71 but maybe this works? https://github.com/DiscordHooks/travis-ci-discord-webhook).

Just jotting some things down.

https://slack.github.com/

https://docs.travis-ci.com/user/notifications/#configuring-slack-notifications

https://docs.travis-ci.com/user/notifications/#configuring-irc-notifications

I'd like some way to ping for real time conversation and problem solving but at the same time, the asynchronous nature of GitHub/email is nice so that I don't lose track of to-do items and such (can leave stuff in my inbox and address it when I'm free). I'm sure others feel the same way. IRC seems simple enough though (just have to find a good app).

**Comment by nickdesaulniers** [comment]
Please file a new issue to discuss this.

**Comment by nathanchance** [comment]
Yes sorry, should have done that a few messages ago. I will do it shortly.
